SQLALCHEMY_DATABASE_URI = 'mysql+cymysql://root:20001127000@127.0.0.1/product'
SECRET_KEY = 'This_1s_A_Secret'

# 开启数据库查询性能测试
SQLALCHEMY_RECORD_QUERIES = True

# 性能测试的阀值
DATABASE_QUERY_TIMEOUT = 0.5

SQLALCHEMY_TRACK_MODIFICATIONS = True

WTF_CSRF_CHECK_DEFAULT = False

SQLALCHEMY_ECHO = True

